/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_fm_adtest_tool_AdHelper */

#ifndef _Included_cn_fm_adtest_tool_AdHelper
#define _Included_cn_fm_adtest_tool_AdHelper
#ifdef __cplusplus
extern "C" {
#endif

char *jstringToChar(JNIEnv *env, jstring jstr);

/*
 * Class:     cn_fm_adtest_tool_AdHelper
 * Method:    testC
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_fm_adtest_tool_AdHelper_testC
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
